
version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - ${ES_HTTP_PORT}:${ES_HTTP_PORT}
      - ${ES_TRANSPORT_PORT}:${ES_TRANSPORT_PORT}
    environment:
      - network.host=${ES_NETWORK_HOST}
      - discovery.type=single-node
      - node.name=es01
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    environment:
      - network.host=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://elastic:${ES_HTTP_PORT}
    depends_on:
      - elastic
      - fluentd
    logging:
      driver: fluentd 
      options:
        fluentd-address: localhost:${FLUENTD_PORT}
        tag: '{{.Name}}'
  fluentd:
    image: fluentd
    ports:
      - ${FLUENTD_PORT}:${FLUENTD_PORT}/tcp
      - ${FLUENTD_PORT}:${FLUENTD_PORT}/udp
        #   volumes:
        #-
    depends_on:
      - elastic
      
