
version: '3'
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    ports:
      - ${ES_HTTP_PORT}:${ES_HTTP_PORT}
      - ${ES_TRANSPORT_PORT}:${ES_TRANSPORT_PORT}
    environment:
      - network.host=${ES_NETWORK_HOST}
      - discovery.type=single-node
      - node.name=es01
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    environment:
      - network.host=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://elastic:${ES_HTTP_PORT}
    depends_on:
      - elastic
      - fluentd
    logging:
      driver: fluentd 
      options:
        fluentd-address: localhost:${FLUENTD_PORT}
        tag: '{{.Name}}'
  fluentd:
    container_name: fluentd
    build: ./fluentd
    ports:
      - ${FLUENTD_PORT}:${FLUENTD_PORT}/tcp
      - ${FLUENTD_PORT}:${FLUENTD_PORT}/udp
    volumes:
      - ./fluentd/:/fluentd/etc/
    depends_on:
      - elastic
  nginx:
    image: nginx:latest     
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - elastic
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:${FLUENTD_PORT}
        tag: '{{.Name}}'
