
version: '3'
services:  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
