version: '3'
services:
  rabbitmq:
    build: . 
          #    environment:
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./certs/:/etc/rabbitmq/certs/
    ports:
      - 5672:5672
      - 15672:15672  
      - 5671:5671
      - 61613:61613
      - 15671:15671
